version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=grupo3
      - MYSQL_DATABASE=grupo3
      - MYSQL_USER=grupo3
      - MYSQL_PASSWORD=grupo3
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3256:3306

volumes:
  mariadb_data:

  version: '2.3'
  services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_USER: dbproducto
      POSTGRES_PASSWORD: grupo3
      POSTGRES_DB: grupo3
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    ports:
      - "5152:5432"

  volumes:
  timescaledb_data: